#
# Task: Create an LXC container on Proxmox for Jenkins
#
# @author Remko Naber
#

- name: Create LXC VM
  community.general.proxmox:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ natlab_user_password }}"

    node: "{{ proxmox_node }}"
    vmid: "{{ node.vmid }}"
    hostname: "{{ node.hostname }}"
    ostemplate: "{{ lxc_ostemplate }}"
    unprivileged: true
    state: present

    description: Jenkins LXC
    pubkey: "{{ natlab_user_ssh_key }}"

    disk: local-lvm:4 # Basically storage and 4 GB disk
    memory: 4096
    swap: 2048
    netif: "{{ node.netif }}"
    features:
      - nesting=1 # This ensures the container actually runs faster then a snail

- name: Start LXC VM
  community.general.proxmox:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ natlab_user_password }}"

    node: "{{ proxmox_node }}"
    vmid: "{{ node.vmid }}"
    hostname: "{{ node.hostname }}"
    unprivileged: true
    state: started
