#
# Task: Stop LXC container on Proxmox PVE
#
# @author Remko Naber
#

- name: Stop LXC VM
  community.general.proxmox:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ natlab_user_password }}"

    node: pve
    vmid: "{{ node.vmid }}"
    hostname: "{{ node.hostname }}"
    unprivileged: true
    state: stopped
